### ISSUE TITLE
Criar release para versionar no packagist e definir stable

### ISSUE THREAD

**Issue by danielcosta** [gpupo/common-sdk#1]
Olá,

Você poderia criar um release (1.0.0 por exemplo) para que fosse possível usar uma versão específica ou família de versão (~1.0), ao invés de usar dev-master?

Com isso é possível alterar a minimum-stability no composer.json para "stable", pois aplicações em produção deveriam somente usar pacotes stable com versões definidas.

Isso é importante quando se lida com packages de terceiros em ambientes mais "corporativos" e é preciso ter o controle das versões que se instala nos ambientes.

Obrigado!

**Comment by gpupo** [comment]
Olá Daniel!
Você tem razão.

Criei https://github.com/gpupo/common-sdk/releases/tag/1.0.0

Confirme o sucesso no uso?

**Comment by danielcosta** [comment]
Apareceu no packagist, mas uma coisa que percebi é que o common/sdk usa gpupo/common e gpupo/cache que também estão dessa forma. Nossa aplicação requer versões stable e com isso não estamos conseguindo passar a usar seu pacote principal que é o submarino-sdk.

Estou forkando todos aqui pra ajustar os composer.json e posso mandar PR neles depois, aí se você aceitar é só versionar em seguida.

**Comment by gpupo** [comment]
Sempre é bom ter ajuda :)

**Comment by gpupo** [comment]
Resolvido na release V1.0.1 da common-sdk e também na versão 1.0 da submarino-sdk
