### ISSUE TITLE
Compatibilidade PHP 7.2

### ISSUE THREAD

**Issue by lucascolette** [gpupo/common-sdk#7]
É possível este package ser compatível com a versão 7.2 do PHP?

Pergunto pois alguns outros packages como o `gpupo/cnova-sdk` requerem esta lib.

**Comment by gpupo** [comment]
Olá @lucascolette !
Para que você possa usar a cnova-sdk, criei a release 1.4.0 que especifica as versões de dependências compatíveis => https://github.com/gpupo/cnova-sdk/releases/tag/1.4.0

Este ano estou atualizando e melhorando várias das minhas SDKs. Já estão atualizadas a mercadolivre-sdk e a mercadopago-sdk, assim como a shipping-services e a brazilian-cars. Isto demanda bastante código novo na common e na common-sdk que já demandam php7.3 para que tenham um tempo de vida maior.

Fique atento à cnova-sdk pois não a melhoro desde 2017 e não sei como está sua comunicação com a API da Cnova.

Neste mês devo trabalhar na submarino-sdk, em sua versão nova conectada ao hub da b2w.

Sua limitação quanto à versão do PHP se dá em função do que ? 
[]s

**Comment by lucascolette** [comment]
Oi @gpupo 

Obrigado pelas instruções. Estamos tentando integrar com a Cnova via Guzzle mesmo. A API deles é bem confusa e tem, por exemplo, 2 versões dela em produção (v2 e v4). Isso é péssimo :(

A limitação é que nossa aplicação ainda não é compatível com o PHP 7.3, apenas 7.2.

Mas enfim, iremos acompanhar a evolução dos seus SDKs. Btw, parabéns pelo trabalho.

Vou fechar essa issue, pois ela foi apenas uma curiosidade.

Abraços!
